project_id = "uatmgqwqdnqlwpyduhwn"

[functions.telegram-webhook]
verify_jwt = false

[functions.messenger-webhook]
verify_jwt = false

[functions.facebook-oauth]
verify_jwt = false

[functions.manage-channel]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.visitor-chat]
verify_jwt = false

[functions.mcp]
verify_jwt = false
