// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-my-chatbot.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_chatbot_default = defineTool({
  name: "get_my_chatbot",
  title: "Get my chatbot",
  description: "Return the signed-in user's Jawabi chatbot: name, language, dialect, tone, welcome and fallback messages, custom instructions, business fields, bot_mode, and active status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("chatbots").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No chatbot found for this user." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { chatbot: data }
    };
  }
});

// src/lib/mcp/tools/list-knowledge.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_knowledge_default = defineTool2({
  name: "list_knowledge_items",
  title: "List knowledge base items",
  description: "List knowledge base entries (text, FAQ, files, URLs, social, images) for the signed-in user's chatbot. Optionally filter by type.",
  inputSchema: {
    type: z.enum(["text", "faq", "file", "url", "social", "image"]).optional().describe("Filter by knowledge item type."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data: chatbot, error: cbErr } = await sb.from("chatbots").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (cbErr) return { content: [{ type: "text", text: cbErr.message }], isError: true };
    if (!chatbot) return { content: [{ type: "text", text: "No chatbot found." }] };
    let q = sb.from("knowledge_items").select("id, type, title, question, answer, content, file_name, file_url, created_at").eq("chatbot_id", chatbot.id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-faq.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var add_faq_default = defineTool3({
  name: "add_faq",
  title: "Add FAQ",
  description: "Add a question/answer pair to the signed-in user's chatbot knowledge base. Use for teaching the bot specific answers.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Short title/label for this FAQ."),
    question: z2.string().trim().min(1).describe("The customer question."),
    answer: z2.string().trim().min(1).describe("The answer the bot should give.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, question, answer }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data: chatbot } = await sb.from("chatbots").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!chatbot) return { content: [{ type: "text", text: "No chatbot found." }], isError: true };
    const { data, error } = await sb.from("knowledge_items").insert({ chatbot_id: chatbot.id, type: "faq", title, question, answer }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    try {
      await fetch(`${process.env.SUPABASE_URL}/functions/v1/generate-embedding`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${ctx.getToken()}`,
          apikey: process.env.SUPABASE_PUBLISHABLE_KEY
        },
        body: JSON.stringify({ item_id: data.id })
      });
    } catch (e) {
      console.warn("embedding trigger failed:", e);
    }
    return {
      content: [{ type: "text", text: `FAQ added (id: ${data.id}).` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/add-text-knowledge.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var add_text_knowledge_default = defineTool4({
  name: "add_text_knowledge",
  title: "Add text knowledge",
  description: "Add a free-form text passage (business info, policy, product description) to the signed-in user's chatbot knowledge base.",
  inputSchema: {
    title: z3.string().trim().min(1).describe("Short title/label for this passage."),
    content: z3.string().trim().min(1).describe("The text content the bot should learn.")
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ title, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data: chatbot } = await sb.from("chatbots").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!chatbot) return { content: [{ type: "text", text: "No chatbot found." }], isError: true };
    const { data, error } = await sb.from("knowledge_items").insert({ chatbot_id: chatbot.id, type: "text", title, content }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Text knowledge added (id: ${data.id}).` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_notifications_default = defineTool5({
  name: "list_notifications",
  title: "List recent notifications",
  description: "List recent notifications (sale intents, human-handover requests, unclear questions) for the signed-in user's chatbot.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data: chatbot } = await sb.from("chatbots").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!chatbot) return { content: [{ type: "text", text: "No chatbot found." }] };
    const { data, error } = await sb.from("notifications").select("id, type, title, channel, contact_identifier, last_message, created_at").eq("chatbot_id", chatbot.id).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-chatbot-settings.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var update_chatbot_settings_default = defineTool6({
  name: "update_chatbot_settings",
  title: "Update chatbot settings",
  description: "Update the signed-in user's chatbot persona and behavior: name, tone, dialect, welcome/fallback messages, custom instructions, and bot_mode.",
  inputSchema: {
    name: z5.string().trim().min(1).optional(),
    tone: z5.enum(["professional", "friendly", "casual", "formal"]).optional(),
    dialect: z5.enum(["palestinian", "formal"]).optional(),
    welcome_message: z5.string().optional(),
    fallback_message: z5.string().optional(),
    custom_instructions: z5.string().optional(),
    bot_mode: z5.enum(["inquiries_only", "inquiries_sales", "inquiries_sales_followup"]).optional(),
    is_active: z5.boolean().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const updates = Object.fromEntries(
      Object.entries(input).filter(([, v]) => v !== void 0)
    );
    if (Object.keys(updates).length === 0) {
      return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
    }
    const sb = supabaseForUser6(ctx);
    const { data, error } = await sb.from("chatbots").update(updates).eq("user_id", ctx.getUserId()).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No chatbot found." }], isError: true };
    return {
      content: [{ type: "text", text: "Chatbot updated." }],
      structuredContent: { chatbot: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uatmgqwqdnqlwpyduhwn";
var mcp_default = defineMcp({
  name: "jawabi-mcp",
  title: "Jawabi MCP",
  version: "0.1.0",
  instructions: "Tools for the Jawabi chatbot platform. Each signed-in user has ONE chatbot. Use these tools to read the user's chatbot configuration, list and add knowledge base entries (FAQs and text passages), review recent customer notifications, and update chatbot persona/behavior settings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_chatbot_default,
    list_knowledge_default,
    add_faq_default,
    add_text_knowledge_default,
    list_notifications_default,
    update_chatbot_settings_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
